site_name: Color-Platform User Guides
nav:
    - Web-Wallet: index.md
    - ColorCLI: colorcli.md
    - ColorDaemon: colord.md
    - Faucet: faucet.md
    - Explorer: Explorer_setup.md

theme: material


